### ISSUE TITLE
broadcast BTC transaction error

### ISSUE THREAD

**Issue by dfoderick** [the-bitcoin-token/bitcoin-source-api#11]
Enable BTC testnet to send a transaction. Error below
BTC Testnet › sendTransaction › should build and broadcast a transaction
```
    ApiError: Server error: status      400 Bad Request
    headers     {"date":"Tue, 26 Feb 2019 01:19:31 GMT","content-type":"text/html; charset=utf-8","content-length":"97","connection":"close","set-cookie":["__cfduid=d8a3c2d21048090cc6b208542d78cdb231551143971; expires=Wed, 26-Feb-20 01:19:31 GMT; path=/; domain=.bitpay.com; HttpOnly"],"x-powered-by":"Express","x-ratelimit-limit":"60","x-ratelimit-remaining":"58","access-control-allow-origin":"*","access-control-allow-methods":"GET, HEAD, PUT, POST, OPTIONS","access-control-allow-headers":"Origin, X-Requested-With, Content-Type, Accept, Content-Length, Cache-Control, cf-connecting-ip","etag":"W/\"61-TRJ/L/3Vq+WeRCIOhZhBMA\"","vary":"Accept-Encoding","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","server":"cloudflare","cf-ray":"4aee957c8a917790-LAX"}
    message     **16: mandatory-script-verify-flag-failed (Signature hash type missing or not understood). Code:-26**
    request     post https://test-insight.bitpay.com/api/tx/send
    data        {"rawtx":"01000000017cfc59a6ba3254221a1c739bf7c69d49ea5fc0d97dbc1d38f8bda1e8a38c8431010000006b483045022100c74875987eeb5c7004d3b6f150fddb8cb4cd5d0069c8677601280e5ebfd7567702200a8ab66e71dafe88fc9cb8b74127845b7a7350bdc1727c9442162a8b2f049799412103364d45fc5432491ee4e5cb048e9f4d2bfdc95b4452f733ea5593c0e7af22a5faffffffff0222020000000000001976a91473cb587449d1772aa702293911686c3e20957ecc88acc82bbb01000000001976a91473cb587449d1772aa702293911686c3e20957ecc88ac00000000"}

      19 | request\t${method} ${url}${requestData ? `\ndata\t${requestData}` : ''}`
      20 | 
    > 21 |     return new ApiError('Server error', details)
      22 |   } else if (error.request) {
      23 |     return new ApiError('Communication error', 'Service unavailable')
      24 |   }

      at axiosToApiError (src/util.js:21:12)
      at axiosToApiError (src/util.js:42:11)
```

**Comment by dfoderick** [comment]
**mandatory-script-verify-flag-failed (Signature hash type missing or not understood). Code:-26**

**Comment by dfoderick** [comment]
Fixed in altcoins branch.
BTC uses sighash_all instead of forkid
